name: Packing source

# manual trigger only
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  obfuscate:
    name: Obfuscate & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run light obfuscation
        # Assumes you have "obf:light" script in package.json
        run: npm run obf:light

      - name: Prepare release zip (exclude dev folders)
        run: |
          set -e
          RM=release.zip
          # remove previous artifact if any
          if [ -f "$RM" ]; then rm -f "$RM"; fi

          # Create zip of repo root but exclude common unwanted folders/files.
          # Adjust --exclude patterns if you want different excludes.
          zip -r "$RM" . -x "node_modules/*" ".git/*" ".github/*" "release.zip" "release.zip" "backup_obf*" "backup_before_edit/*" "dist_release/*"

          echo "Created $RM"

      - name: Upload obfuscated artifact
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-release
          path: release.zip
